[package]
name = "ijs_live_team_totals"
version = "0.4.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.17.1"
toml = "0.8.1"
serde = "1.0.164"
serde_derive = "1.0.164"
text_io = "0.1.12"
rust_xlsxwriter = "0.52.0"
iced = { git = "https://github.com/iced-rs/iced" }
async-std = "1.12.0"
native-dialog = "0.6.4"
human-sort = "0.2.2"
once_cell = "1.18.0"