[package]
name = "ijs_live_team_totals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
reqwest = "0.11.18"
scraper = "0.16.0"
stringmetrics = "2.2.2"
toml = "0.7.4"
serde = "1.0.164"
serde_derive = "1.0.164"
text_io = "0.1.12"