[package]
name = "ijs_live_team_totals"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.17.1"
toml = "0.8.1"
serde = "1.0.164"
serde_derive = "1.0.164"
text_io = "0.1.12"
rust_xlsxwriter = "0.49.0"
iced = "0.10.0"